parameters:
  - name: suiteName
    displayName: select suite to run
    type: string
    default: project-a
    values:
      - project-a
      - project-b
      - project-c
  - name: suiteEnvironment
    displayName: select environment to run suite on
    type: string
    default: test
    values:
      - test
      - develop
      - stage
      - production

trigger: none # this is a manually run build, not an automated post-PR build, so no automated triggers to invoke needed

variables:
  npm_config_cache: $(Pipeline.Workspace)/npm

pool:
  vmImage: # YOUR-BUILD-AGENT-NAME-HERE

stages:
  - stage: cypressIntegrationTests
    displayName: 'run cypress tests'

    jobs:
      - template: azure-templates/cypress-template.yml
        parameters:
          selectedSuiteName: ${{ parameters.suiteName }}
          selectedSuiteEnv: ${{ parameters.suiteEnvironment }}
          username: # YOUR-CYPRESS-USERNAME-HERE
          password: # YOUR-CYPRESS-PASSWORD-HERE
