parameters:
  - name: selectedSuiteName
    type: string
  - name: selectedSuiteEnv
    type: string
  - name: username
    type: string
  - name: password
    type: string

# set a 'default' under 'type' with empty string if optional param

jobs:
  - job: runCypressTests
    displayName: running cypress tests for ${{ paramaters.selectedProjectName }} on environment ${{ parameters.selectedProjectEnv }}
    pool: #YOUR-BUILD-AGENT-NAME
    steps:
      - task: NodeTool@0 #https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/node-tool-v0?view=azure-pipelines
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"

      - task: Cache@2
        inputs:
          key: 'version_NodeJs16x | npm | "$(Agent.OS)" | package-lock.json'
          path: $(npm_config_cache)
        displayName: Cache npm

      - task: Npm@1 #https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/npm-v1?view=azure-pipelines
        inputs:
          command: "install"

      - ${{ if eq(parameters.selectedSuiteName, 'project-a')  }}:
          - script: npx cypress run --spec "cypress/e2e/project-a/integration/*.cy.js"
            displayName: "running ${{ parameters.selectedSuiteName }}"
            env:
              CYPRESS_USERNAME: ${{ parameters.username }}
              CYPRESS_PASSWORD: ${{ parameters.password }}
              CYPRESS_suiteEnv: ${{ parameters.selectedSuiteEnv }} # can also hardcode the values in here
              CYPRESS_suiteName: ${{ parameters.selectedSuiteName }}
              # anything delcared as CYPRESS_ will become an env var Cypress can access
              # can add extra env vars for specific suites only or change vars based on suite

      - ${{ if eq(parameters.selectedSuiteName, 'project-b')  }}:
          - script: npx cypress run --spec "cypress/e2e/project-b/integration/*.cy.js"
            displayName: "running ${{ parameters.selectedSuiteName }}"
            env:
              CYPRESS_USERNAME: ${{ parameters.username }}
              CYPRESS_PASSWORD: ${{ parameters.password }}
              CYPRESS_suiteEnv: ${{ parameters.selectedSuiteEnv }}
              CYPRESS_suiteName: ${{ parameters.selectedSuiteName }}
